#pragma once
#include "config.h"

#define TURRET_USTEPS_TO_DEGREES ((NEMA_STEPS_PER_REV * TURRET_GEAR_RATIO * (1UL << TURRET_USTEPS)) / 360.0f)

#define TURRET_VELOCITY_RPS ((LUNA_HZ / 360.0f) * (TURRET_REVERSE ? -1.0f : 1.0f))
#define TURRET_USTEPS_PER_SECOND (TURRET_VELOCITY_RPS * TURRET_USTEPS_TO_DEGREES * 360)
#define TURRET_USTEPS_PER_PERIOD (TURRET_USTEPS_PER_SECOND / ESP_CLOCK)
#define TURRET_VELOCITY TURRET_USTEPS_PER_PERIOD

#define TURRET_HOMING_VELOCITY_RPS (TURRET_HOMING_RPS * (TURRET_REVERSE ? -1.0f : 1.0f))
#define TURRET_HOMING_USTEPS_PER_SECOND (TURRET_HOMING_VELOCITY_RPS * TURRET_USTEPS_TO_DEGREES * 360)
#define TURRET_HOMING_USTEPS_PER_PERIOD (TURRET_HOMING_USTEPS_PER_SECOND / ESP_CLOCK)
#define TURRET_HOMING_VELOCITY TURRET_HOMING_USTEPS_PER_PERIOD

#define SWEEPER_USTEPS_TO_DEGREES ((NEMA_STEPS_PER_REV * SWEEPER_GEAR_RATIO * (1UL << SWEEPER_USTEPS)) / 360.0f)

#define SWEEPER_HOMING_VELOCITY_RPS (SWEEPER_HOMING_RPS * (SWEEPER_REVERSE ? -1.0f : 1.0f))
#define SWEEPER_HOMING_USTEPS_PER_SECOND (SWEEPER_HOMING_VELOCITY_RPS * SWEEPER_USTEPS_TO_DEGREES * 360.0f)
#define SWEEPER_HOMING_USTEPS_PER_PERIOD (SWEEPER_HOMING_USTEPS_PER_SECOND / ESP_CLOCK)
#define SWEEPER_HOMING_VELOCITY SWEEPER_HOMING_USTEPS_PER_PERIOD

#define W_BASE (TURRET_VELOCITY_RPS * 1.0f / 360.0f)
